### ISSUE TITLE
Allow slash-delimited paths

### ISSUE THREAD

**Issue by colinodell** [dflydev/dflydev-dot-access-data#21]
I'd like to use this library in the next major release of `league/commonmark`.  Unfortunately I'm blocked by the fact that v1 of my library uses array paths with slashes (`foo/bar`) instead of dots (`foo.bar`) and I'd like to preserve that for backward-compatibility reasons.

I'd therefore like to propose the ability for the library to allow for both `.` and `/` as key path delimiters.

I have working code I'd be happy to contribute, but it would rely on ~~#18 (merged)~~ and #20 to be merged first to avoid merge conflicts.

**Comment by simensen** [comment]
Is it a configuration / opt-in thing to support both `.` and `/`, or would it be an "always allow both" sort of situation?

**Comment by colinodell** [comment]
I'd strongly prefer this to be "always allow both" so that anyone receiving a `DataInterface` instance knows they can safely use either delimiter; otherwise, they might try to use `/` not knowing that it wasn't configured/enabled that way and get unexpected results.

I'd also be open to an alternative approach that allows `Data` to be extended and the delimiters to be set in that new class.  Perhaps `Data` could have a static protected property or method like `$delimiters` or `getDelimiters()` that I could override.  This has a similar effect where anyone using my subclass can safely assume that slashes are available.

One other potential approach could be setting the allowed delimiters in the constructor as an optional second parameter.  This doesn't alleviate my primary concern but it would be a workable solution I could live with :)

I would **not** be in favor of something that configures this behavior statically as I'd like some level of guarantee that other code can't modify the settings globally in a way that could prevent `/` from being used.

Open to your thoughts here!

**Comment by colinodell** [comment]
@simensen I have implemented both possible approaches for your review:

 - #24, where the delimiters are hard-coded and cannot be changed (my personal preference)
 - #25, where the delimiters can be configured via the constructor

I'd appreciate any feedback you might have.  And if/when you choose to merge one, please make sure to only merge one and close the other :wink:

**Comment by simensen** [comment]
I am closing this as I think the merging of #24 resolves this issue.
