### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by dhensby** [dflydev/dflydev-dot-access-data#5]
It looks like master has some commits that haven't made it into a release (adding the `has` method).

It'd be great if that could be released as a v1.1.0 release 👼

**Comment by samdjstevens** [comment]
@simensen any chance of a new release with this in? Would be helpful for a project I'm currently using the package in.

**Comment by grasmash** [comment]
@simensen Would you consider cutting a release? I'd be happy to co-maintain if you're interested.

**Comment by simensen** [comment]
A new v1.1.0 release has been tagged. Let me know if there are any problems. Thanks.

**Comment by grasmash** [comment]
@simensen Thank you!

**Comment by Danielss89** [comment]
This can be closed.
